# Generated by Django 4.2.6 on 2023-10-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="age_range",
            field=models.CharField(default=0, max_length=50, verbose_name="연령대"),
            preserve_default=False,
        ),
    ]
