# Generated by Django 4.2.6 on 2023-10-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_age_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age_range",
            field=models.CharField(
                choices=[
                    ("10대", "10대"),
                    ("20대", "20대"),
                    ("30대", "30대"),
                    ("40대", "40대"),
                    ("50대", "50대"),
                    ("60대", "60대"),
                    ("70대", "70대"),
                    ("80대", "80대"),
                    ("선택", "선택"),
                ],
                default="선택",
                max_length=50,
                verbose_name="연령대",
            ),
        ),
    ]
