#!/bin/bash

# error to exit process
set -o errexit

# pipeline ar executed successfully
set -o pipefail

# sciprt to exit unitialized variable is usesd
set -o nounset

# don't have a Postgres user enviornment variable
if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user="postgres"
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

python << END
import sys
import time
import psycopg2
suggest_unrecoverable_after = 30
start = time.time()
while True:
    try:
        psycopg2.connect(
            dbname="${POSTGRES_DB}",
            user="${POSTGRES_USER}",
            password="${POSTGRES_PASSWORD}",
            host="${POSTGRES_HOST}",
            port="${POSTGRES_PORT}",
        )
        break
    except psycopg2.OperationalError as error:
        sys.stderr.write("Waiting for PostgreSQL to become avaliable ...\n")
        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write(f" This is taking too longer than expected. The following exception may be indicative of unrecoverable error: {error}\n")
        time.sleep(1)
END

>&2 echo "PostgreSQL is avaliable"

exec "$@"