#!/bin/bash

# error to exit process
set -o errexit

# pipeline ar executed successfully
set -o pipefail

# sciprt to exit unitialized variable is usesd
set -o nounset

python backend/manage.py migrate --no-input
python backend/manage.py collectstatic --no-input
exec python backend/manage.py runserver 0.0.0.0:8000