version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: 1eejuhwany/bloodsugar-app
    command: poetry run python3 manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped