# Generated by Django 4.2.6 on 2023-11-07 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodSugarManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empty_stomach",
                    models.PositiveIntegerField(default=0, help_text="공복"),
                ),
                ("morning", models.PositiveIntegerField(default=0, help_text="아침")),
                ("lunch", models.PositiveIntegerField(default=0, help_text="점심")),
                ("evening", models.PositiveIntegerField(default=0, help_text="저녁")),
                ("created_at", models.DateField(auto_now_add=True, help_text="생성 일자")),
                (
                    "manager",
                    models.ForeignKey(
                        help_text="작성자",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
