# Generated by Django 4.2.6 on 2023-11-09 10:25

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bloodsugarmanager",
            options={"verbose_name": "혈당 관리", "verbose_name_plural": "혈당 관리"},
        ),
        migrations.AlterField(
            model_name="bloodsugarmanager",
            name="created_at",
            field=models.DateField(
                default=config.utils.get_current_date, help_text="생성 일자"
            ),
        ),
    ]
