# Generated by Django 4.2.6 on 2023-11-26 05:12

import config.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("management", "0002_alter_bloodsugarmanager_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(default=None, help_text="메모 내용")),
                (
                    "created_at",
                    models.DateField(
                        default=config.utils.get_current_date, help_text="생성 일자"
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        help_text="작성자",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "메모",
                "verbose_name_plural": "메모",
            },
        ),
        migrations.AddField(
            model_name="bloodsugarmanager",
            name="feedback",
            field=models.ForeignKey(
                default=1,
                help_text="메모",
                on_delete=django.db.models.deletion.CASCADE,
                to="management.feedbackmanager",
            ),
            preserve_default=False,
        ),
    ]
