# Generated by Django 4.2.6 on 2023-11-26 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_feedbackmanager_bloodsugarmanager_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodsugarmanager",
            name="feedback",
            field=models.ForeignKey(
                help_text="메모",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="management.feedbackmanager",
            ),
        ),
    ]
