# Generated by Django 4.2.6 on 2023-11-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_alter_bloodsugarmanager_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackmanager",
            name="content",
            field=models.TextField(default=None, help_text="메모 내용", null=True),
        ),
    ]
