# Generated by Django 4.2.6 on 2023-12-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_alter_feedbackmanager_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodsugarmanager",
            name="evening",
        ),
        migrations.RemoveField(
            model_name="bloodsugarmanager",
            name="lunch",
        ),
        migrations.RemoveField(
            model_name="bloodsugarmanager",
            name="morning",
        ),
        migrations.AddField(
            model_name="bloodsugarmanager",
            name="after_evening",
            field=models.PositiveIntegerField(default=0, help_text="저녁 식후"),
        ),
        migrations.AddField(
            model_name="bloodsugarmanager",
            name="after_lunch",
            field=models.PositiveIntegerField(default=0, help_text="점심 식후"),
        ),
        migrations.AddField(
            model_name="bloodsugarmanager",
            name="after_morning",
            field=models.PositiveIntegerField(default=0, help_text="아침 식후"),
        ),
        migrations.AddField(
            model_name="bloodsugarmanager",
            name="before_evening",
            field=models.PositiveIntegerField(default=0, help_text="저녁 식전"),
        ),
        migrations.AddField(
            model_name="bloodsugarmanager",
            name="before_lunch",
            field=models.PositiveIntegerField(default=0, help_text="점심 식전"),
        ),
        migrations.AddField(
            model_name="bloodsugarmanager",
            name="before_morning",
            field=models.PositiveIntegerField(default=0, help_text="아침 식전"),
        ),
    ]
